#!/bin/sh -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    update-alternatives --remove x-www-browser /usr/bin/firefox-bin
    update-alternatives --remove gnome-www-browser /usr/bin/firefox-bin
fi

if [ "$1" = "remove" ]; then
    rm -f /opt/firefox-bin/components/compreg.dat \
          /opt/firefox-bin/components/xpti.dat
    rm -rf /opt/firefox-bin/updates
fi

#DEBHELPER#
